/**
 * js/schedule.js — 日程管理
 */
const Schedule = {
  allSchedules: [],
  currentFilter: 'all',
  editingId: null,

  async render() {
    try { this.allSchedules = await API.get('/api/schedules'); } catch (e) { console.error(e); return; }
    this.filterAndRender();
  },

  filterAndRender() {
    let list = this.allSchedules;
    if (this.currentFilter !== 'all') list = list.filter(s => s.category === this.currentFilter);

    const pending = list.filter(s => !s.completed);
    const completed = list.filter(s => s.completed);
    const groups = {};
    pending.forEach(s => { if (!groups[s.date]) groups[s.date] = []; groups[s.date].push(s); });
    const sortedDates = Object.keys(groups).sort();

    const wds = ['日','一','二','三','四','五','六'];
    const tLabel = { morning:'上午', afternoon:'下午', evening:'晚上', bedtime:'睡前' };
    const cEmoji = { travel:'\u2708', pet:'\u{1F431}', intimacy:'\u2665', family:'\u25C6', custom:'\u25CB' };
    const bCls = { travel:'badge-travel', pet:'badge-pet', intimacy:'badge-intimacy', family:'badge-family', custom:'badge-custom' };
    const bLabel = { travel:'出行', pet:'猫咪', intimacy:'亲密', family:'家庭', custom:'自定义' };

    function renderItem(s) {
      const cCls = s.completed ? ' completed' : '';
      return '<div class="schedule-item' + cCls + '" data-sid="' + s.id + '">' +
        '<button class="todo-check' + (s.completed?' checked':'') +
        '" onclick="Schedule.toggleComplete(\'' + s.id + '\')" title="' + (s.completed?'取消完成':'标记完成') + '">' +
        (s.completed?'\u2713':'') + '</button>' +
        '<div class="item-icon">' + (cEmoji[s.category]||'\u{1F4CC}') + '</div>' +
        '<div class="item-info"><div class="item-title">' + s.title + '</div>' +
        '<div class="item-desc">' + (s.person||'') + (s.description?' · '+s.description:'') + '</div></div>' +
        '<span class="item-badge ' + (bCls[s.category]||'badge-custom') + '">' + (bLabel[s.category]||'日程') + '</span>' +
        '<span class="todo-time">' + (tLabel[s.time]||'') + '</span>' +
        (!s.autoGenerated ?
          '<div class="item-actions"><button class="btn btn-outline" style="font-size:12px;padding:3px 8px;" onclick="Schedule.editSchedule(\'' + s.id + '\',event)">编辑</button>' +
          '<button class="btn btn-danger" style="font-size:12px;padding:3px 8px;" onclick="Schedule.deleteCustom(\'' + s.id + '\')">删除</button></div>'
        : '<div class="item-actions"><button class="btn btn-outline" style="font-size:12px;padding:3px 8px;" onclick="Schedule.editSchedule(\'' + s.id + '\',event)">编辑</button></div>') +
        '</div>';
    }

    let html = sortedDates.map(date => {
      const d = new Date(date + 'T00:00:00+08:00');
      const today = new Date(); today.setHours(0,0,0,0);
      const isPast = d < today;
      return '<div class="schedule-group"><div class="schedule-date-header" style="color:'+(isPast?'#999':'#5C5750')+'">' +
        date + ' 星期' + wds[d.getDay()] + (d.getTime()===today.getTime()?' · 今天':'') + '</div>' +
        groups[date].map(renderItem).join('') + '</div>';
    }).join('');

    // 已完成折叠区
    if (completed.length > 0) {
      html += '<div class="completed-section"><div class="completed-toggle" onclick="document.getElementById(\'completedList\').classList.toggle(\'show\');this.classList.toggle(\'open\')">' +
        '<span>&#x2705; 已完成 (' + completed.length + ')</span><span class="toggle-arrow">&#x25BC;</span></div>' +
        '<div class="completed-list" id="completedList">' + completed.map(renderItem).join('') + '</div></div>';
    }

    document.getElementById('scheduleList').innerHTML = html || '<div class="empty-state">没有符合条件的日程</div>';
  },

  async toggleComplete(id) {
    const s = this.allSchedules.find(s => s.id === id); if (!s) return;
    try {
      if (s.completed) await API.post('/api/schedules/' + id + '/uncomplete');
      else await API.post('/api/schedules/' + id + '/complete');
      App.showToast(s.completed ? '已恢复未完成' : '已完成');
      await this.render();
    } catch(e) { console.error(e); }
  },

  /* ====== 添加/编辑弹窗 ====== */
  showAddModal() {
    this.editingId = null;
    document.querySelector('#addScheduleModal h4').textContent = '添加新日程';
    document.getElementById('newTitle').value = '';
    document.getElementById('newDate').value = new Date().toISOString().slice(0,10);
    document.getElementById('newTime').value = 'evening';
    document.getElementById('newPerson').value = '';
    document.getElementById('newCategory').value = 'custom';
    document.getElementById('newDesc').value = '';
    document.getElementById('addScheduleModal').classList.add('show');
    document.getElementById('newTitle').focus();
  },

  editSchedule(id, e) {
    e.stopPropagation();
    const s = this.allSchedules.find(s => s.id === id); if (!s) return;
    this.editingId = id;
    document.querySelector('#addScheduleModal h4').textContent = '编辑日程';
    document.getElementById('newTitle').value = s.title || '';
    document.getElementById('newDate').value = s.date || '';
    document.getElementById('newTime').value = s.time || 'evening';
    document.getElementById('newPerson').value = s.person || '';
    document.getElementById('newCategory').value = s.category || 'custom';
    document.getElementById('newDesc').value = s.description || '';
    document.getElementById('addScheduleModal').classList.add('show');
    document.getElementById('newTitle').focus();
  },

  hideAddModal() { document.getElementById('addScheduleModal').classList.remove('show'); this.editingId = null; },

  async saveNewSchedule() {
    const title = document.getElementById('newTitle').value.trim();
    const date = document.getElementById('newDate').value;
    if (!title || !date) { App.showToast('请填写标题和日期'); return; }

    const data = {
      title, date,
      time: document.getElementById('newTime').value,
      person: document.getElementById('newPerson').value.trim(),
      category: document.getElementById('newCategory').value,
      description: document.getElementById('newDesc').value.trim(),
    };

    try {
      if (this.editingId) { await API.put('/api/schedules/' + this.editingId, data); App.showToast('已更新'); }
      else { await API.post('/api/schedules', { ...data, repeatRule: 'none' }); App.showToast('已添加'); }
      this.hideAddModal(); await this.render();
    } catch(e) { App.showToast('操作失败'); }
  },

  async deleteCustom(id) {
    if (!confirm('确定删除此日程？')) return;
    try { await API.del('/api/schedules/' + id); App.showToast('已删除'); await this.render(); }
    catch(e) { console.error(e); }
  },
};

// 筛选事件绑定
document.addEventListener('DOMContentLoaded', () => {
  document.getElementById('filterChips')?.addEventListener('click', (e) => {
    const chip = e.target.closest('.chip'); if (!chip) return;
    document.querySelectorAll('.filter-chips .chip').forEach(c => c.classList.remove('active'));
    chip.classList.add('active');
    Schedule.currentFilter = chip.dataset.filter; Schedule.filterAndRender();
  });
});
