/**
 * js/schedule.js — 日程提醒
 */
const Schedule = {
  currentFilter: 'all',
  allSchedules: [],

  async render() {
    try {
      this.allSchedules = await API.get('/api/schedules');
      this.filterAndRender();
    } catch (e) {
      document.getElementById('scheduleList').innerHTML =
        '<div class="empty-state">加载日程失败，请检查服务是否启动</div>';
    }
  },

  filterAndRender() {
    let filtered = this.allSchedules;
    if (this.currentFilter !== 'all') {
      filtered = this.allSchedules.filter(s => s.category === this.currentFilter);
    }

    // 按日期分组
    const groups = {};
    filtered.forEach(s => {
      if (!groups[s.date]) groups[s.date] = [];
      groups[s.date].push(s);
    });

    const sortedDates = Object.keys(groups).sort();
    const container = document.getElementById('scheduleList');

    if (sortedDates.length === 0) {
      container.innerHTML = '<div class="empty-state">没有符合条件的日程</div>';
      return;
    }

    const weekDays = ['日', '一', '二', '三', '四', '五', '六'];
    const timeLabel = { morning: '上午', afternoon: '下午', evening: '晚上', bedtime: '睡前' };
    const catEmoji = { travel: '✈️', pet: '🐱', intimacy: '❤️', family: '🏡', custom: '📝' };
    const badgeClass = { travel: 'badge-travel', pet: 'badge-pet', intimacy: 'badge-intimacy', family: 'badge-family', custom: 'badge-custom' };
    const badgeLabel = { travel: '出行', pet: '猫咪', intimacy: '亲密', family: '家庭', custom: '自定义' };

    container.innerHTML = sortedDates.map(date => {
      const d = new Date(date + 'T00:00:00+08:00');
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      const isToday = d.getTime() === today.getTime();
      const isPast = d.getTime() < today.getTime();
      const dateLabel = `${date} 星期${weekDays[d.getDay()]}${isToday ? ' · 今天' : ''}`;

      const items = groups[date].map(s => {
        const completedCls = s.completed ? ' completed' : '';
        return `
          <div class="schedule-item${completedCls}" data-sid="${s.id}">
            <button class="todo-check${s.completed ? ' checked' : ''}"
                    onclick="Schedule.toggleComplete('${s.id}')"
                    title="标记完成">${s.completed ? '✓' : ''}</button>
            <div class="item-icon">${catEmoji[s.category] || '📌'}</div>
            <div class="item-info">
              <div class="item-title">${s.title}</div>
              <div class="item-desc">${s.person || ''}${s.description ? ' · ' + s.description : ''}</div>
            </div>
            <span class="item-badge ${badgeClass[s.category] || 'badge-custom'}">${badgeLabel[s.category] || '日程'}</span>
            <span class="todo-time">${timeLabel[s.time] || ''}</span>
            ${!s.autoGenerated ? `
            <div class="item-actions">
              <button class="btn btn-outline" onclick="Schedule.editSchedule('${s.id}', event)" style="font-size:12px;padding:4px 10px;">编辑</button>
              <button class="btn btn-danger" onclick="Schedule.deleteCustom('${s.id}')">删除</button>
            </div>` : `
            <div class="item-actions">
              <button class="btn btn-outline" onclick="Schedule.editSchedule('${s.id}', event)" style="font-size:12px;padding:4px 10px;">编辑</button>
            </div>`}
          </div>
        `;
      }).join('');

      return `
        <div class="schedule-group">
          <div class="schedule-date-header" style="color: ${isPast ? 'var(--text-muted)' : 'var(--text-secondary)'}">
            ${dateLabel}
          </div>
          ${items}
        </div>
      `;
    }).join('');
  },

  async toggleComplete(id) {
    try {
      await API.post(`/api/schedules/${id}/complete`);
      await this.render();
      App.showToast('已标记完成 ✓');
    } catch (e) {
      console.error('Toggle complete failed:', e);
    }
  },

  async deleteCustom(id) {
    if (!confirm('确定要删除这个日程吗？')) return;
    try {
      await API.del(`/api/schedules/${id}`);
      await this.render();
      App.showToast('日程已删除');
    } catch (e) {
      console.error('Delete failed:', e);
    }
  },

  setFilter(filter) {
    this.currentFilter = filter;
    this.filterAndRender();

    // 更新 chip 样式
    document.querySelectorAll('#filterChips .chip').forEach(c => {
      c.classList.toggle('active', c.dataset.filter === filter);
    });
  },

  editingId: null,

  showAddModal() {
    this.editingId = null;
    document.getElementById('addScheduleModal').querySelector('h4').textContent = '添加新日程';
    document.getElementById('newTitle').value = '';
    document.getElementById('newDate').value = new Date().toISOString().slice(0, 10);
    document.getElementById('newTime').value = 'evening';
    document.getElementById('newPerson').value = '';
    document.getElementById('newCategory').value = 'custom';
    document.getElementById('newDesc').value = '';
    document.getElementById('addScheduleModal').classList.add('show');
    document.getElementById('newTitle').focus();
  },

  editSchedule(id, event) {
    event.stopPropagation();
    const s = this.allSchedules.find(s => s.id === id);
    if (!s) return;

    this.editingId = id;
    document.getElementById('addScheduleModal').querySelector('h4').textContent = '编辑日程';
    document.getElementById('newTitle').value = s.title || '';
    document.getElementById('newDate').value = s.date || '';
    document.getElementById('newTime').value = s.time || 'evening';
    document.getElementById('newPerson').value = s.person || '';
    document.getElementById('newCategory').value = s.category || 'custom';
    document.getElementById('newDesc').value = s.description || '';
    document.getElementById('addScheduleModal').classList.add('show');
    document.getElementById('newTitle').focus();
  },

  hideAddModal() {
    document.getElementById('addScheduleModal').classList.remove('show');
    this.editingId = null;
  },

  async saveNewSchedule() {
    const title = document.getElementById('newTitle').value.trim();
    const date = document.getElementById('newDate').value;
    const time = document.getElementById('newTime').value;
    const person = document.getElementById('newPerson').value.trim();
    const category = document.getElementById('newCategory').value;
    const desc = document.getElementById('newDesc').value.trim();

    if (!title || !date) {
      App.showToast('请填写标题和日期');
      return;
    }

    try {
      if (this.editingId) {
        // 编辑现有日程
        await API.put(`/api/schedules/${this.editingId}`, {
          title, date, time, person, category, description: desc,
        });
        App.showToast('日程已更新 ✓');
      } else {
        // 新建日程
        await API.post('/api/schedules', {
          title, date, time, person, category, description: desc, repeatRule: 'none',
        });
        App.showToast('日程已添加 ✓');
      }
      this.hideAddModal();
      await this.render();
    } catch (e) {
      console.error('Save schedule failed:', e);
      App.showToast('操作失败，请重试');
    }
  },
};
