/**
 * server.js — 老郦家 家庭管理系统
 * Express 后端 + 全量 API
 */
const express = require('express');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');
const multer = require('multer');

const { generateAllSchedules } = require('./lib/scheduler');
const { formatDate } = require('./lib/holidays');
const { startScheduler, testSend, loadConfig } = require('./lib/mailer');

// ==================== 基础配置 ====================
const app = express();
const PORT = process.env.PORT || 3456;
const DATA_DIR = path.join(__dirname, 'data');

// ==================== 中间件 ====================
app.use(express.json());
app.use(express.static(__dirname, {
  setHeaders: (res) => {
    res.set('Cache-Control', 'no-cache, no-store, must-revalidate');
  }
}));

// ==================== 工具函数 ====================
function readJSON(name) {
  try {
    return JSON.parse(fs.readFileSync(path.join(DATA_DIR, name), 'utf-8'));
  } catch (_) { return null; }
}
function writeJSON(name, data) {
  fs.writeFileSync(path.join(DATA_DIR, name), JSON.stringify(data, null, 2), 'utf-8');
}

// ==================== 首页 ====================
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

// ==================== 家庭信息 API ====================
app.get('/api/family', (req, res) => {
  res.json(readJSON('family.json') || {});
});

// ==================== 首页 Dashboard API ====================
app.get('/api/dashboard', (req, res) => {
  const family = readJSON('family.json') || {};
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const feedLog = readJSON('feed-log.json') || {};

  const now = new Date();
  const today = formatDate(now);
  
  // 今日日程（含已完成）
  const allScheds = generateAllSchedules(stored);
  const todaySchedules = allScheds.filter(s => s.date === today);
  
  // 即将到来（不含今日，最多10条）
  const upcomingSchedules = allScheds
    .filter(s => s.date > today && !s.completed)
    .slice(0, 10);

  // 纪念日
  const currentYear = now.getFullYear();
  const anniversaries = (family.members || [])
    .filter(m => m.birthday)
    .map(m => {
      const [bMonth, bDay] = m.birthday.split('-').map(Number);
      let bDate = new Date(currentYear, bMonth - 1, bDay);
      if (bDate < now) bDate = new Date(currentYear + 1, bMonth - 1, bDay);
      const daysUntil = Math.ceil((bDate - now) / 86400000);
      return {
        memberId: m.id,
        name: m.name,
        birthday: m.birthday,
        date: formatDate(bDate),
        daysUntil,
        nextAge: bDate.getFullYear() === currentYear ? m.age : m.age + 1,
        emoji: m.type === 'cat' ? '🐱' : (m.name === '郦赟' ? '👨' : '👩'),
        color: m.color,
      };
    })
    .sort((a, b) => a.daysUntil - b.daysUntil);

  // 猫咪状态
  const lastFed = feedLog.lastFedFreezeDry || '';
  const lastWater = feedLog.lastRefillWater || '';
  const daysSinceFed = lastFed ? Math.floor((now - new Date(lastFed)) / 86400000) : 0;
  const daysSinceWater = lastWater ? Math.floor((now - new Date(lastWater)) / 86400000) : 0;

  // 下次喂食/加水日期
  let nextFedDate = new Date(lastFed);
  nextFedDate.setDate(nextFedDate.getDate() + 2);
  let nextWaterDate = new Date(lastWater);
  nextWaterDate.setDate(nextWaterDate.getDate() + 3);

  res.json({
    today,
    todaySchedules,
    upcomingSchedules,
    anniversaries,
    catStatus: {
      lastFedFreezeDry: lastFed,
      daysSinceFed,
      nextFed: formatDate(nextFedDate),
      lastRefillWater: lastWater,
      daysSinceWater,
      nextWaterCheck: formatDate(nextWaterDate),
    },
    memberCount: family.members?.length || 0,
  });
});

// ==================== 日程 API ====================
app.get('/api/schedules', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const allScheds = generateAllSchedules(stored);
  res.json(allScheds);
});

app.post('/api/schedules', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const entry = {
    id: `custom-${uuidv4().slice(0, 8)}`,
    title: req.body.title || '新日程',
    date: req.body.date || formatDate(new Date()),
    time: req.body.time || 'evening',
    person: req.body.person || '',
    category: req.body.category || 'custom',
    description: req.body.description || '',
    repeatRule: req.body.repeatRule || 'none',
    autoGenerated: false,
    createdAt: new Date().toISOString(),
  };
  stored.custom.push(entry);
  writeJSON('schedules.json', stored);
  res.json(entry);
});

app.put('/api/schedules/:id', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const id = req.params.id;

  // 更新自定义日程
  let idx = stored.custom.findIndex(s => s.id === id);
  if (idx !== -1) {
    stored.custom[idx] = { ...stored.custom[idx], ...req.body, updatedAt: new Date().toISOString() };
    writeJSON('schedules.json', stored);
    return res.json(stored.custom[idx]);
  }

  // 更新已完成日程
  let cIdx = stored.completed.findIndex(s => s.id === id);
  if (cIdx !== -1) {
    stored.completed[cIdx] = { ...stored.completed[cIdx], ...req.body, updatedAt: new Date().toISOString() };
    writeJSON('schedules.json', stored);
    return res.json(stored.completed[cIdx]);
  }

  // 自动生成的日程 → 转为自定义保存
  const allGen = generateAllSchedules(stored);
  const genIdx = allGen.findIndex(s => s.id === id);
  if (genIdx !== -1) {
    stored.completed = stored.completed.filter(c => c.id !== id);
    const newCustom = { ...allGen[genIdx], ...req.body, autoGenerated: false, updatedAt: new Date().toISOString() };
    stored.custom.push(newCustom);
    writeJSON('schedules.json', stored);
    return res.json(newCustom);
  }

  res.status(404).json({ error: '未找到该日程' });
});

// 标记完成
app.post('/api/schedules/:id/complete', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const id = req.params.id;

  // 从自定义中找
  const target = [...(stored.custom || [])].find(s => s.id === id);
  if (target) {
    stored.completed.push({ ...target, completed: true, completedAt: new Date().toISOString() });
    writeJSON('schedules.json', stored);
    return res.json({ success: true, schedule: { ...target, completed: true } });
  }
  
  // 从自动生成中找（用 scheduler 重建）
  const allGen = generateAllSchedules(stored);
  const genTarget = allGen.find(s => s.id === id);
  if (genTarget) {
    stored.completed.push({ ...genTarget, completed: true, completedAt: new Date().toISOString() });
    writeJSON('schedules.json', stored);
    return res.json({ success: true, schedule: { ...genTarget, completed: true } });
  }

  res.status(404).json({ error: '未找到该日程' });
});

// 取消完成
app.post('/api/schedules/:id/uncomplete', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  stored.completed = (stored.completed || []).filter(c => c.id !== req.params.id);
  writeJSON('schedules.json', stored);
  res.json({ success: true });
});

// 删除自定义日程
app.delete('/api/schedules/:id', (req, res) => {
  let stored = readJSON('schedules.json') || { completed: [], custom: [] };
  stored.custom = (stored.custom || []).filter(s => s.id !== req.params.id);
  writeJSON('schedules.json', stored);
  res.json({ success: true });
});

// ==================== 家规 API ====================
app.get('/api/rules', (req, res) => {
  res.json(readJSON('rules.json') || []);
});

app.post('/api/rules', (req, res) => {
  const rules = readJSON('rules.json') || [];
  const rule = {
    id: `rule-${uuidv4().slice(0, 8)}`,
    title: req.body.title || '新家规',
    content: req.body.content || '',
    createdAt: new Date().toISOString(),
  };
  rules.push(rule);
  writeJSON('rules.json', rules);
  res.json(rule);
});

app.put('/api/rules/:id', (req, res) => {
  const rules = readJSON('rules.json') || [];
  const idx = rules.findIndex(r => r.id === req.params.id);
  if (idx === -1) return res.status(404).json({ error: '未找到该家规' });
  rules[idx] = { ...rules[idx], ...req.body, updatedAt: new Date().toISOString() };
  writeJSON('rules.json', rules);
  res.json(rules[idx]);
});

app.delete('/api/rules/:id', (req, res) => {
  let rules = readJSON('rules.json') || [];
  rules = rules.filter(r => r.id !== req.params.id);
  writeJSON('rules.json', rules);
  res.json({ success: true });
});

// ==================== 留言板 API ====================
app.get('/api/messages', (req, res) => {
  const messages = readJSON('messages.json') || [];
  messages.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
  res.json(messages);
});

app.post('/api/messages', (req, res) => {
  const messages = readJSON('messages.json') || [];
  const msg = {
    id: `msg-${uuidv4().slice(0, 8)}`,
    content: req.body.content || '',
    createdAt: new Date().toISOString(),
    replies: [],
  };
  messages.push(msg);
  writeJSON('messages.json', messages);
  res.json(msg);
});

app.post('/api/messages/:id/reply', (req, res) => {
  const messages = readJSON('messages.json') || [];
  const msg = messages.find(m => m.id === req.params.id);
  if (!msg) return res.status(404).json({ error: '未找到该留言' });

  const reply = {
    id: `reply-${uuidv4().slice(0, 8)}`,
    content: req.body.content || '',
    createdAt: new Date().toISOString(),
  };
  msg.replies.push(reply);
  writeJSON('messages.json', messages);
  res.json(reply);
});

app.delete('/api/messages/:id', (req, res) => {
  let messages = readJSON('messages.json') || [];
  messages = messages.filter(m => m.id !== req.params.id);
  writeJSON('messages.json', messages);
  res.json({ success: true });
});

// ==================== 相册 API ====================
if (!fs.existsSync(path.join(DATA_DIR, 'photos.json'))) {
  writeJSON('photos.json', []);
}

const photoStorage = multer.diskStorage({
  destination: path.join(DATA_DIR, 'photos'),
  filename: (req, file, cb) => {
    const ext = path.extname(file.originalname) || '.jpg';
    cb(null, `${uuidv4()}${ext}`);
  },
});

const upload = multer({
  storage: photoStorage,
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
    const allowed = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.heic'];
    if (allowed.includes(path.extname(file.originalname).toLowerCase())) cb(null, true);
    else cb(new Error('不支持的图片格式'));
  },
});

app.get('/api/photos', (req, res) => {
  const photos = readJSON('photos.json') || [];
  photos.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
  res.json(photos);
});

app.post('/api/photos', upload.single('photo'), (req, res) => {
  if (!req.file) return res.status(400).json({ error: '请选择图片' });

  const photos = readJSON('photos.json') || [];
  const entry = {
    id: `photo-${uuidv4().slice(0, 8)}`,
    filename: req.file.filename,
    originalName: req.file.originalname,
    caption: req.body.caption || '',
    tag: req.body.tag || 'family',
    createdAt: new Date().toISOString(),
    size: req.file.size,
  };
  photos.push(entry);
  writeJSON('photos.json', photos);
  res.json(entry);
});

app.delete('/api/photos/:id', (req, res) => {
  let photos = readJSON('photos.json') || [];
  const p = photos.find(p => p.id === req.params.id);
  if (p) {
    const fp = path.join(DATA_DIR, 'photos', p.filename);
    if (fs.existsSync(fp)) fs.unlinkSync(fp);
  }
  photos = photos.filter(p => p.id !== req.params.id);
  writeJSON('photos.json', photos);
  res.json({ success: true });
});

app.use('/photos', express.static(path.join(DATA_DIR, 'photos')));

// ==================== 邮件配置 API ====================
app.get('/api/email-config', (req, res) => {
  const cfg = loadConfig();
  res.json({
    enabled: cfg.enabled,
    recipient: cfg.recipient,
    schedule: cfg.schedule,
    hasAuth: !!(cfg.smtp?.auth?.pass),
    smtpUser: cfg.smtp?.auth.user || '',
  });
});

app.put('/api/email-config', (req, res) => {
  const cur = loadConfig();
  const updated = {
    ...cur,
    enabled: req.body.enabled !== undefined ? req.body.enabled : cur.enabled,
    recipient: req.body.recipient || cur.recipient,
    schedule: req.body.schedule || cur.schedule,
    smtp: {
      ...(cur.smtp || {}),
      auth: {
        user: req.body.smtpUser || (cur.smtp?.auth?.user || ''),
        pass: req.body.smtpPass || (cur.smtp?.auth?.pass || ''),
      },
    },
  };
  writeJSON('email-config.json', updated);
  emailConfig = updated;
  res.json({ success: true, message: '邮件配置已保存，重启服务后定时任务生效' });
});

app.post('/api/email-config/test', async (req, res) => {
  try {
    await testSend();
    res.json({ success: true, message: '测试邮件发送成功' });
  } catch (e) {
    res.json({ success: false, message: '发送失败: ' + e.message });
  }
});

// ==================== 启动服务 ====================
app.listen(PORT, () => {
  const os = require('os');
  const ifaces = os.networkInterfaces();
  const ips = [];
  Object.values(ifaces).forEach(iface => {
    iface.forEach(addr => {
      if (addr.family === 'IPv4' && !addr.internal) ips.push(addr.address);
    });
  });

  console.log(`[老郦家] 服务已启动 (GLM版 v2.0)`);
  console.log(`   本机: http://localhost:${PORT}`);
  ips.forEach(ip => console.log(`   手机: http://${ip}:${PORT}`));

  startScheduler();
});
