/**
 * server.js — 老郦家 家庭管理系统后端
 */
const express = require('express');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');
const { generateAllSchedules } = require('./lib/scheduler');
const { formatDate } = require('./lib/holidays');
const { startScheduler, testSend, loadConfig } = require('./lib/mailer');

const app = express();
const PORT = process.env.PORT || 3456;

// 数据目录
const DATA_DIR = path.join(__dirname, 'data');

// 中间件
app.use(express.json());
app.use(express.static(__dirname));

// 工具函数：读取 JSON 文件
function readJSON(filename) {
  const filePath = path.join(DATA_DIR, filename);
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

// 工具函数：写入 JSON 文件
function writeJSON(filename, data) {
  const filePath = path.join(DATA_DIR, filename);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
}

// ==================== 首页 ====================
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

// ==================== 家庭信息 API ====================
app.get('/api/family', (req, res) => {
  const data = readJSON('family.json');
  res.json(data);
});

app.put('/api/family', (req, res) => {
  const data = readJSON('family.json');
  const updated = { ...data, ...req.body };
  writeJSON('family.json', updated);
  res.json(updated);
});

// ==================== 日程 API ====================
app.get('/api/schedules', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const allSchedules = generateAllSchedules(stored);
  res.json(allSchedules);
});

app.post('/api/schedules', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const newSchedule = {
    id: uuidv4(),
    ...req.body,
    autoGenerated: false,
    createdAt: new Date().toISOString(),
  };

  // 如果是完成操作的特殊处理
  if (req.body.action === 'complete') {
    const scheduleId = req.body.id;
    // 从生成的日程或自定义日程中查找
    const allGenerated = generateAllSchedules(stored);
    const target = allGenerated.find(s => s.id === scheduleId);

    if (target) {
      // 移除之前的完成记录（如果存在）
      stored.completed = stored.completed.filter(c => c.id !== scheduleId);
      stored.completed.push({ ...target, completed: true, completedAt: new Date().toISOString() });
      writeJSON('schedules.json', stored);
      return res.json({ success: true, schedule: { ...target, completed: true } });
    }
    return res.status(404).json({ error: 'Schedule not found' });
  }

  // 添加自定义日程
  stored.custom.push(newSchedule);
  writeJSON('schedules.json', stored);
  res.json(newSchedule);
});

app.put('/api/schedules/:id', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const id = req.params.id;

  // 查找并更新自定义日程
  const idx = stored.custom.findIndex(s => s.id === id);
  if (idx !== -1) {
    stored.custom[idx] = { ...stored.custom[idx], ...req.body, updatedAt: new Date().toISOString() };
    writeJSON('schedules.json', stored);
    return res.json(stored.custom[idx]);
  }

  // 查找并更新已完成日程
  const cIdx = stored.completed.findIndex(s => s.id === id);
  if (cIdx !== -1) {
    stored.completed[cIdx] = { ...stored.completed[cIdx], ...req.body, updatedAt: new Date().toISOString() };
    writeJSON('schedules.json', stored);
    return res.json(stored.completed[cIdx]);
  }

  // 如果是自动生成的日程（不在 custom/completed 中），将其转为自定义并保存
  const allGenerated = generateAllSchedules(stored);
  const genIdx = allGenerated.findIndex(s => s.id === id);
  if (genIdx !== -1) {
    // 从已完成列表中移除（如果有冲突的完成记录）
    stored.completed = stored.completed.filter(c => c.id !== id);
    const newCustom = { ...allGenerated[genIdx], ...req.body, autoGenerated: false, updatedAt: new Date().toISOString() };
    stored.custom.push(newCustom);
    writeJSON('schedules.json', stored);
    return res.json(newCustom);
  }

  res.status(404).json({ error: 'Schedule not found' });
});

app.delete('/api/schedules/:id', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const id = req.params.id;

  stored.custom = stored.custom.filter(s => s.id !== id);
  stored.completed = stored.completed.filter(s => s.id !== id);
  writeJSON('schedules.json', stored);
  res.json({ success: true });
});

app.post('/api/schedules/:id/complete', (req, res) => {
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const id = req.params.id;

  // 从所有可能的来源查找日程
  const allGenerated = generateAllSchedules(stored);
  const target = allGenerated.find(s => s.id === id);

  if (target) {
    stored.completed = stored.completed.filter(c => c.id !== id);
    stored.completed.push({ ...target, completed: true, completedAt: new Date().toISOString() });
    writeJSON('schedules.json', stored);
    return res.json({ success: true, schedule: { ...target, completed: true } });
  }

  res.status(404).json({ error: 'Schedule not found' });
});

// ==================== 家规 API ====================
app.get('/api/rules', (req, res) => {
  const rules = readJSON('rules.json') || [];
  res.json(rules);
});

app.post('/api/rules', (req, res) => {
  const rules = readJSON('rules.json') || [];
  const newRule = {
    id: `rule-${uuidv4().slice(0, 8)}`,
    title: req.body.title || '新规则',
    content: req.body.content || '',
    order: rules.length + 1,
    createdAt: new Date().toISOString(),
  };
  rules.push(newRule);
  writeJSON('rules.json', rules);
  res.json(newRule);
});

app.put('/api/rules/:id', (req, res) => {
  const rules = readJSON('rules.json') || [];
  const id = req.params.id;
  const idx = rules.findIndex(r => r.id === id);
  if (idx !== -1) {
    rules[idx] = { ...rules[idx], ...req.body, updatedAt: new Date().toISOString() };
    writeJSON('rules.json', rules);
    return res.json(rules[idx]);
  }
  res.status(404).json({ error: 'Rule not found' });
});

app.delete('/api/rules/:id', (req, res) => {
  let rules = readJSON('rules.json') || [];
  const id = req.params.id;
  rules = rules.filter(r => r.id !== id);
  // 重新排序
  rules.forEach((r, i) => { r.order = i + 1; });
  writeJSON('rules.json', rules);
  res.json({ success: true });
});

// ==================== 首页面板 API ====================
app.get('/api/dashboard', (req, res) => {
  const today = formatDate(new Date());
  const family = readJSON('family.json');
  const stored = readJSON('schedules.json') || { completed: [], custom: [] };
  const allSchedules = generateAllSchedules(stored);

  // 今日待办
  const todaySchedules = allSchedules.filter(s => s.date === today && !s.completed);

  // 最近待办（未来7天）
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 7);
  const weekEnd = formatDate(tomorrow);
  const upcomingSchedules = allSchedules.filter(
    s => s.date >= today && s.date <= weekEnd && !s.completed
  ).slice(0, 10);

  // 猫咪状态
  const lastFed = family?.meta?.lastFedFreezeDry || '2026-06-20';
  const lastWater = family?.meta?.lastRefillWater || '2026-06-19';
  const daysSinceFed = Math.floor((new Date(today) - new Date(lastFed)) / (1000 * 60 * 60 * 24));
  const daysSinceWater = Math.floor((new Date(today) - new Date(lastWater)) / (1000 * 60 * 60 * 24));

  res.json({
    today,
    todaySchedules,
    upcomingSchedules,
    catStatus: {
      lastFedFreezeDry: lastFed,
      lastRefillWater: lastWater,
      daysSinceFed,
      daysSinceWater,
      nextFed: daysSinceFed >= 2 ? '今天' : `${2 - daysSinceFed}天后`,
      nextWaterCheck: daysSinceWater >= 3 ? '今天' : `${3 - daysSinceWater}天后`,
    },
    memberCount: family?.members?.length || 0,
  });
});

// ==================== 喂食记录 API ====================
app.post('/api/feed-log', (req, res) => {
  const logs = readJSON('feed-log.json') || [];
  const entry = {
    id: uuidv4(),
    type: req.body.type || 'feeding', // 'feeding' | 'water'
    date: req.body.date || formatDate(new Date()),
    timestamp: new Date().toISOString(),
    note: req.body.note || '',
  };
  logs.unshift(entry);
  writeJSON('feed-log.json', logs);

  // 更新 lastFed/lastRefill 日期
  const family = readJSON('family.json');
  if (entry.type === 'feeding') {
    family.meta.lastFedFreezeDry = entry.date;
  } else if (entry.type === 'water') {
    family.meta.lastRefillWater = entry.date;
  }
  writeJSON('family.json', family);

  res.json(entry);
});

app.get('/api/feed-log', (req, res) => {
  const logs = readJSON('feed-log.json') || [];
  const limit = parseInt(req.query.limit) || 20;
  res.json(logs.slice(0, limit));
});

// ==================== 邮件配置 API ====================
app.get('/api/email-config', (req, res) => {
  const cfg = loadConfig();
  // 不返回密码
  const safe = {
    enabled: cfg.enabled,
    recipient: cfg.recipient,
    schedule: cfg.schedule,
    hasAuth: !!(cfg.smtp?.auth?.user && cfg.smtp?.auth?.pass),
    smtpUser: cfg.smtp?.auth?.user || '',
  };
  res.json(safe);
});

app.put('/api/email-config', (req, res) => {
  const current = loadConfig();
  const updated = {
    ...current,
    enabled: req.body.enabled !== undefined ? req.body.enabled : current.enabled,
    recipient: req.body.recipient || current.recipient,
    schedule: req.body.schedule || current.schedule,
    smtp: {
      ...current.smtp,
      auth: {
        user: req.body.smtpUser || current.smtp.auth.user,
        pass: req.body.smtpPass || current.smtp.auth.pass,
      },
    },
  };
  fs.writeFileSync(path.join(DATA_DIR, 'email-config.json'), JSON.stringify(updated, null, 2), 'utf-8');
  res.json({ success: true, message: '邮件配置已保存，需重启服务生效定时任务' });
});

app.post('/api/email-config/test', async (req, res) => {
  try {
    await testSend();
    res.json({ success: true, message: '测试邮件发送成功' });
  } catch (e) {
    res.json({ success: false, message: '发送失败: ' + e.message });
  }
});

// ==================== 留言板 API ====================
app.get('/api/messages', (req, res) => {
  const messages = readJSON('messages.json') || [];
  messages.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
  res.json(messages);
});

app.post('/api/messages', (req, res) => {
  const messages = readJSON('messages.json') || [];
  const newMsg = {
    id: `msg-${uuidv4().slice(0, 8)}`,
    content: req.body.content || '',
    createdAt: new Date().toISOString(),
    replies: [],
  };
  messages.push(newMsg);
  writeJSON('messages.json', messages);
  res.json(newMsg);
});

app.post('/api/messages/:id/reply', (req, res) => {
  const messages = readJSON('messages.json') || [];
  const msg = messages.find(m => m.id === req.params.id);
  if (!msg) return res.status(404).json({ error: 'Message not found' });
  const reply = {
    id: `reply-${uuidv4().slice(0, 8)}`,
    content: req.body.content || '',
    createdAt: new Date().toISOString(),
  };
  msg.replies.push(reply);
  writeJSON('messages.json', messages);
  res.json(reply);
});

app.delete('/api/messages/:id', (req, res) => {
  let messages = readJSON('messages.json') || [];
  messages = messages.filter(m => m.id !== req.params.id);
  writeJSON('messages.json', messages);
  res.json({ success: true });
});

// ==================== 启动服务 ====================
app.listen(PORT, () => {
  const os = require('os');
  const ifaces = os.networkInterfaces();
  const ips = [];
  Object.values(ifaces).forEach(iface => {
    iface.forEach(addr => {
      if (addr.family === 'IPv4' && !addr.internal) ips.push(addr.address);
    });
  });

  console.log(`🏠 老郦家 家庭管理系统已启动`);
  console.log(`   本机访问: http://localhost:${PORT}`);
  ips.forEach(ip => console.log(`   手机访问: http://${ip}:${PORT}`));
  console.log(`   API 地址: http://localhost:${PORT}/api`);

  // 启动邮件定时任务
  startScheduler();
});
