/**
 * lib/scheduler.js — 日程计算引擎（未来7天）
 */
const { isHoliday, isWorkDay, getAdjustedFlightDates, formatDate } = require('./holidays');

const SCHEDULE_RANGE_DAYS = 7;

function generateAllSchedules(stored) {
  const now = new Date();
  const today = formatDate(now);
  const completed = (stored && stored.completed) || [];
  const custom = (stored && stored.custom) || [];
  
  // 生成未来 N 天的自动日程
  const autoSchedules = [];

  for (let i = 0; i < SCHEDULE_RANGE_DAYS; i++) {
    const d = new Date(now);
    d.setDate(d.getDate() + i);
    const dateStr = formatDate(d);
    const dayOfWeek = d.getDay(); // 0=日 1=一 ... 6=六

    // === 1. 郦赟航班：周五无锡→北京 ===
    if (dayOfWeek === 5) {
      autoSchedules.push(makeSchedule('flight-to-bj', `郦赟回京（无锡硕放→北京首都）`, dateStr, 'morning', 'travel', '郦赟', '每周五固定航班'));
      
      // 购票提醒（提前30天，如果在这个范围内的话）
      for (let td = 30; td <= 32; td++) {
        const ticketDate = new Date(d);
        ticketDate.setDate(ticketDate.getDate() - td);
        const ticketStr = formatDate(ticketDate);
        if (ticketStr >= today && ticketStr <= dateStr) {
          autoSchedules.push(makeSchedule(`ticket-${dateStr}`, `购票提醒：${dateStr} 回京机票`, ticketStr, 'morning', 'travel', '郦赟', '提前购买享优惠'));
        }
      }
    }

    // === 2. 郦赟返锡：周日北京→无锡 ===
    if (dayOfWeek === 0) {
      autoSchedules.push(makeSchedule('flight-to-wx', `郦赟返锡（北京首都→无锡硕放）`, dateStr, 'evening', 'travel', '郦赟', '每周日固定航班'));

      // 购票提醒
      for (let td = 30; td <= 32; td++) {
        const ticketDate = new Date(d);
        ticketDate.setDate(ticketDate.getDate() - td);
        const ticketStr = formatDate(ticketDate);
        if (ticketStr >= today && ticketStr <= dateStr) {
          autoSchedules.push(makeSchedule(`ticket-wx-${dateStr}`, `购票提醒：${dateStr} 返锡机票`, ticketStr, 'morning', 'travel', '郦赟', '提前购买享优惠'));
        }
      }
    }

    // === 节假日航班调整 ===
    const adjustments = getAdjustedFlightDates();
    adjustments.forEach(adj => {
      if (dateStr === adj.goBackEarly) {
        autoSchedules.push(makeSchedule(`flight-adj-${dateStr}`, `郦赟回京（${adj.range}前调）`, dateStr, 'evening', 'travel', '郦赟', `节假日${adj.range}调整`));
      }
      if (dateStr === adj.returnLate) {
        autoSchedules.push(makeSchedule(`flight-wx-adj-${dateStr}`, `郦赟返锡（${adj.range}后调）`, dateStr, 'evening', 'travel', '郦赟', `节假日${adj.range}调整`));
      }
    });

    // === 3. 猫咪冻干：每2天 ===
    // 上次喂食: 2026-06-20
    const lastFed = new Date('2026-06-20');
    let feedDay = new Date(lastFed);
    while (true) {
      feedDay.setDate(feedDay.getDate() + 2);
      const fStr = formatDate(feedDay);
      if (fStr < today) continue;
      if (fStr > dateStr || fStr > formatDate(new Date(now.getTime() + SCHEDULE_RANGE_DAYS * 86400000))) break;
      if (fStr === dateStr) {
        autoSchedules.push(makeSchedule(`feed-fdry-${dateStr}`, `给 LUMI 和弟弟投喂冻干`, dateStr, 'evening', 'pet', '', '每2天一次'));
      }
    }

    // === 4. 水粮检查：每3天 ===
    // 上次加满: 2026-06-19
    const lastWater = new Date('2026-06-19');
    let waterDay = new Date(lastWater);
    while (true) {
      waterDay.setDate(waterDay.getDate() + 3);
      const wStr = formatDate(waterDay);
      if (wStr < today) continue;
      if (wStr > dateStr || wStr > formatDate(new Date(now.getTime() + SCHEDULE_RANGE_DAYS * 86400000))) break;
      if (wStr === dateStr) {
        autoSchedules.push(makeSchedule(`water-check-${dateStr}`, `检查水和猫粮是否充足`, dateStr, 'evening', 'pet', '', '每3天一次'));
      }
    }

    // === 5. 睡前亲亲 ===
    autoSchedules.push(makeSchedule(`kiss-${dateStr}`, `睡前亲亲陈思婧`, dateStr, 'bedtime', 'intimacy', '郦赟', '每日必修课'));
  }

  // 合并：自动日程 + 自定义日程 + 已完成标记
  const completedIds = new Set(completed.map(c => c.id));
  const allSchedules = [...autoSchedules, ...custom].map(s => ({
    ...s,
    completed: completedIds.has(s.id) ? true : false,
  }));

  return allSchedules;
}

function makeSchedule(id, title, date, time, category, person, desc) {
  return { id, title, date, time, category, person: person || '', description: desc || '', autoGenerated: true };
}

module.exports = {
  generateAllSchedules,
  SCHEDULE_RANGE_DAYS,
};
