/**
 * lib/scheduler.js — 日程自动计算引擎
 * 基于规则 + 节假日数据，自动生成未来 N 天的日程
 */
const {
  formatDate, addDays, isHoliday, isWorkday,
  getLastWorkdayBefore, getHolidayForDate,
  getFridayOfWeek, getSundayOfWeek,
  HOLIDAYS_2026,
} = require('./holidays');

// 基准日期
const BASE_FREEZE_FEED = '2026-06-20';  // 上次冻干喂食
const BASE_WATER_CHECK = '2026-06-19';  // 上次水粮加满

// 生成范围：未来 90 天
const SCHEDULE_RANGE_DAYS = 90;

/**
 * 判断某日期是否在任意节假日范围内
 */
function dateInHoliday(dateStr) {
  return getHolidayForDate(dateStr) !== null;
}

/**
 * 获取某周（以dateStr为参考）的假期信息
 * 如果该周五或周日在节假日中，返回对应的假期
 */
function getWeekHolidayInfo(dateStr) {
  const friday = getFridayOfWeek(dateStr);
  const sunday = getSundayOfWeek(dateStr);
  const friInHoliday = getHolidayForDate(friday);
  const sunInHoliday = getHolidayForDate(sunday);
  return { friday, sunday, friInHoliday, sunInHoliday };
}

/**
 * 生成郦赟航班日程
 */
function generateFlightSchedules(startDate, endDate) {
  const schedules = [];
  const processedHolidays = new Set(); // 避免重复生成假期航班

  // 按周遍历
  let weekStart = new Date(startDate + 'T00:00:00+08:00');
  const dayOfWeek = weekStart.getDay();
  // 对齐到周一
  if (dayOfWeek !== 1) {
    weekStart.setDate(weekStart.getDate() + (8 - dayOfWeek) % 7);
    if (dayOfWeek === 1) weekStart.setDate(weekStart.getDate()); // already Monday
    // Actually, let me adjust: align to Monday
    weekStart.setDate(weekStart.getDate() - ((dayOfWeek + 6) % 7));
  }
  
  const end = new Date(endDate + 'T00:00:00+08:00');

  while (weekStart <= end) {
    const monday = formatDate(weekStart);
    const friday = getFridayOfWeek(monday);
    const sunday = getSundayOfWeek(monday);

    // 检查这个周五/周日是否在节假日中
    const friHoliday = getHolidayForDate(friday);
    const sunHoliday = getHolidayForDate(sunday);

    // 处理假期逻辑（每个假期只处理一次）
    if (friHoliday && !processedHolidays.has(friHoliday.name)) {
      processedHolidays.add(friHoliday.name);
      // 生成假期回京航班：节前最后一个工作日
      const returnDate = getLastWorkdayBefore(friHoliday.start);
      if (returnDate >= startDate && returnDate <= endDate) {
        schedules.push({
          id: `flight-return-holiday-${returnDate}`,
          title: `郦赟回京（${friHoliday.name}假期）`,
          type: 'flight',
          person: '郦赟',
          date: returnDate,
          time: 'evening',
          description: `无锡硕放 → 北京首都机场（${friHoliday.name}前最后一个工作日）`,
          repeatRule: 'none',
          category: 'travel',
          autoGenerated: true,
          isHoliday: true,
          holidayName: friHoliday.name,
          direction: 'return',
        });
      }
    }

    if (sunHoliday && !processedHolidays.has(sunHoliday.name)) {
      processedHolidays.add(sunHoliday.name);
      // 生成假期返锡航班：节假日最后一天
      const departDate = sunHoliday.end;
      if (departDate >= startDate && departDate <= endDate) {
        schedules.push({
          id: `flight-depart-holiday-${departDate}`,
          title: `郦赟返锡（${sunHoliday.name}假期）`,
          type: 'flight',
          person: '郦赟',
          date: departDate,
          time: 'evening',
          description: `北京首都机场 → 无锡硕放机场（${sunHoliday.name}最后一天）`,
          repeatRule: 'none',
          category: 'travel',
          autoGenerated: true,
          isHoliday: true,
          holidayName: sunHoliday.name,
          direction: 'depart',
        });
      }
    }

    // 非节假日周五 → 正常回京航班
    if (!friHoliday && friday >= startDate && friday <= endDate) {
      schedules.push({
        id: `flight-return-${friday}`,
        title: '郦赟回京',
        type: 'flight',
        person: '郦赟',
        date: friday,
        time: 'evening',
        description: '无锡硕放 → 北京首都机场',
        repeatRule: 'weekly-friday',
        category: 'travel',
        autoGenerated: true,
        isHoliday: false,
        direction: 'return',
      });
    }

    // 非节假日周日 → 正常返锡航班
    if (!sunHoliday && sunday >= startDate && sunday <= endDate) {
      schedules.push({
        id: `flight-depart-${sunday}`,
        title: '郦赟返锡',
        type: 'flight',
        person: '郦赟',
        date: sunday,
        time: 'evening',
        description: '北京首都机场 → 无锡硕放机场',
        repeatRule: 'weekly-sunday',
        category: 'travel',
        autoGenerated: true,
        isHoliday: false,
        direction: 'depart',
      });
    }

    // 下周
    weekStart.setDate(weekStart.getDate() + 7);
  }

  return schedules;
}

/**
 * 生成购票提醒（航班日期前 30 天）
 */
function generateTicketReminders(flightSchedules) {
  const reminders = [];
  const today = formatDate(new Date());

  for (const flight of flightSchedules) {
    const remindDate = addDays(flight.date, -30);
    // 只生成未来的提醒
    if (remindDate >= today) {
      reminders.push({
        id: `ticket-${flight.id}`,
        title: `购票提醒：${flight.title}`,
        type: 'ticket',
        person: '郦赟',
        date: remindDate,
        time: 'morning',
        description: `${flight.description} — 建议提前购票享优惠`,
        repeatRule: 'none',
        category: 'travel',
        autoGenerated: true,
        relatedFlightDate: flight.date,
      });
    }
  }

  return reminders;
}

/**
 * 生成猫咪冻干喂食日程（每2天）
 */
function generateFeedingSchedules(startDate, endDate) {
  const schedules = [];
  let nextDate = addDays(BASE_FREEZE_FEED, 2);
  const end = endDate;

  while (nextDate <= end) {
    if (nextDate >= startDate) {
      schedules.push({
        id: `feeding-${nextDate}`,
        title: 'LUMI & 弟弟 冻干喂食',
        type: 'feeding',
        person: 'LUMI & 弟弟',
        date: nextDate,
        time: 'evening',
        description: '下班回家后喂冻干，每2天一次',
        repeatRule: 'every2days',
        category: 'pet',
        autoGenerated: true,
      });
    }
    nextDate = addDays(nextDate, 2);
  }

  return schedules;
}

/**
 * 生成水粮检查日程（每3天）
 */
function generateWaterCheckSchedules(startDate, endDate) {
  const schedules = [];
  let nextDate = addDays(BASE_WATER_CHECK, 3);
  const end = endDate;

  while (nextDate <= end) {
    if (nextDate >= startDate) {
      schedules.push({
        id: `water-${nextDate}`,
        title: '检查猫咪水 & 猫粮',
        type: 'check',
        person: 'LUMI & 弟弟',
        date: nextDate,
        time: 'evening',
        description: '下班回家后检查水和猫粮是否充足，不足及时补充',
        repeatRule: 'every3days',
        category: 'pet',
        autoGenerated: true,
      });
    }
    nextDate = addDays(nextDate, 3);
  }

  return schedules;
}

/**
 * 生成每日亲亲提醒
 */
function generateKissSchedules(startDate, endDate) {
  const schedules = [];
  let d = new Date(startDate + 'T00:00:00+08:00');
  const end = new Date(endDate + 'T00:00:00+08:00');

  while (d <= end) {
    const dateStr = formatDate(d);
    schedules.push({
      id: `kiss-${dateStr}`,
      title: '睡前亲亲 💋',
      type: 'kiss',
      person: '郦赟 → 陈思婧',
      date: dateStr,
      time: 'bedtime',
      description: '郦赟睡前亲亲陈思婧，每日必修课 ❤️',
      repeatRule: 'daily',
      category: 'intimacy',
      autoGenerated: true,
    });
    d.setDate(d.getDate() + 1);
  }

  return schedules;
}

/**
 * 主入口：生成所有日程
 * @param {Object} storedSchedules - 数据库中已存储的日程数据 { completed: [], custom: [] }
 * @returns {Array} 合并后的日程列表
 */
function generateAllSchedules(storedSchedules) {
  const today = formatDate(new Date());
  const endDate = addDays(today, SCHEDULE_RANGE_DAYS);

  // 1. 生成航班
  const flights = generateFlightSchedules(today, endDate);

  // 2. 生成购票提醒
  const tickets = generateTicketReminders(flights);

  // 3. 生成猫咪喂食
  const feedings = generateFeedingSchedules(today, endDate);

  // 4. 生成水粮检查
  const waterChecks = generateWaterCheckSchedules(today, endDate);

  // 5. 生成每日亲亲
  const kisses = generateKissSchedules(today, endDate);

  // 合并所有自动生成日程
  let allGenerated = [...flights, ...tickets, ...feedings, ...waterChecks, ...kisses];

  // 去重（按 id）
  const seen = new Set();
  allGenerated = allGenerated.filter(s => {
    if (seen.has(s.id)) return false;
    seen.add(s.id);
    return true;
  });

  // 按日期排序
  allGenerated.sort((a, b) => a.date.localeCompare(b.date));

  // 为所有日程添加 completed 字段
  const stored = storedSchedules || { completed: [], custom: [] };
  const completedIds = new Set(stored.completed.map(c => c.id));
  const customSchedules = stored.custom || [];

  // 合并完成状态
  allGenerated = allGenerated.map(s => ({
    ...s,
    completed: completedIds.has(s.id),
  }));

  // 保留之前已完成但现在已过期（不在生成范围内）的日程
  const generatedIds = new Set(allGenerated.map(s => s.id));
  const oldCompleted = stored.completed.filter(c => !generatedIds.has(c.id));

  // 合并所有日程：生成的 + 自定义 + 旧的已完成
  const allSchedules = [...allGenerated, ...customSchedules, ...oldCompleted];

  return allSchedules;
}

module.exports = {
  generateAllSchedules,
  generateFlightSchedules,
  generateFeedingSchedules,
  generateWaterCheckSchedules,
  generateKissSchedules,
  generateTicketReminders,
};
